// data/icecreams.js
const iceCreams = [
  {
    id: 1,
    name: "Classic Vanilla",
    price: 80,
    rating: 4.5,
    flavor: "Vanilla",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Classic",
    isAvailable: true,
    tagline: "Smooth, creamy, and timeless.",
    image: "http://localhost:7777/images/butter.png"
  },
  {
    id: 2,
    name: "Chocolate Dream",
    price: 100,
    rating: 4.7,
    flavor: "Chocolate",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Classic",
    isAvailable: true,
    tagline: "Rich chocolate indulgence.",
    image: "http://localhost:7777/images/choclate.png"
  },
  {
    id: 3,
    name: "Strawberry Bliss",
    price: 90,
    rating: 4.4,
    flavor: "Strawberry",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fruit",
    isAvailable: true,
    tagline: "Fresh strawberries in every bite.",
    image: "https://picsum.photos/seed/strawberry/300/300"
  },
  {
    id: 4,
    name: "Mango Magic",
    price: 95,
    rating: 4.6,
    flavor: "Mango",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fruit",
    isAvailable: true,
    tagline: "Taste of real Alphonso mangoes.",
    image: "https://picsum.photos/seed/mango/300/300"
  },
  {
    id: 5,
    name: "Butterscotch Crunch",
    price: 110,
    rating: 4.8,
    flavor: "Butterscotch",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Premium",
    isAvailable: true,
    tagline: "Crunchy caramel delight.",
    image: "https://picsum.photos/seed/butterscotch/300/300"
  },
  {
    id: 6,
    name: "Black Currant",
    price: 105,
    rating: 4.3,
    flavor: "Black Currant",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fruit",
    isAvailable: true,
    tagline: "Tangy and refreshing.",
    image: "https://picsum.photos/seed/blackcurrant/300/300"
  },
  {
    id: 7,
    name: "Cookies & Cream",
    price: 120,
    rating: 4.9,
    flavor: "Cookies",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Premium",
    isAvailable: true,
    tagline: "Cookie chunks with creamy joy.",
    image: "https://picsum.photos/seed/cookies/300/300"
  },
  {
    id: 8,
    name: "Pistachio Delight",
    price: 130,
    rating: 4.6,
    flavor: "Pistachio",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Premium",
    isAvailable: true,
    tagline: "Nutty and royal flavor.",
    image: "https://picsum.photos/seed/pistachio/300/300"
  },
  {
    id: 9,
    name: "Chocolate Chip",
    price: 110,
    rating: 4.5,
    flavor: "Chocolate Chip",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Classic",
    isAvailable: true,
    tagline: "Choco chips in every scoop.",
    image: "https://picsum.photos/seed/chocochip/300/300"
  },
  {
    id: 10,
    name: "Mint Choco",
    price: 115,
    rating: 4.2,
    flavor: "Mint Chocolate",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fusion",
    isAvailable: true,
    tagline: "Cool mint meets dark chocolate.",
    image: "https://picsum.photos/seed/mint/300/300"
  },
  {
    id: 11,
    name: "Coffee Crème",
    price: 125,
    rating: 4.6,
    flavor: "Coffee",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fusion",
    isAvailable: true,
    tagline: "Perfect for coffee lovers.",
    image: "https://picsum.photos/seed/coffee/300/300"
  },
  {
    id: 12,
    name: "Blueberry Swirl",
    price: 120,
    rating: 4.4,
    flavor: "Blueberry",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fruit",
    isAvailable: true,
    tagline: "Sweet and tangy blueberry twist.",
    image: "https://picsum.photos/seed/blueberry/300/300"
  },
  {
    id: 13,
    name: "Caramel Treat",
    price: 110,
    rating: 4.5,
    flavor: "Caramel",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Classic",
    isAvailable: true,
    tagline: "Golden caramel goodness.",
    image: "https://picsum.photos/seed/caramel/300/300"
  },
  {
    id: 14,
    name: "Kulfi Malai",
    price: 100,
    rating: 4.7,
    flavor: "Malai",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Indian",
    isAvailable: true,
    tagline: "Traditional creamy kulfi.",
    image: "https://picsum.photos/seed/kulfi/300/300"
  },
  {
    id: 15,
    name: "Kesar Pista",
    price: 140,
    rating: 4.8,
    flavor: "Saffron Pistachio",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Indian",
    isAvailable: true,
    tagline: "Royal saffron delight.",
    image: "https://picsum.photos/seed/kesarpista/300/300"
  },
  {
    id: 16,
    name: "Oreo Blast",
    price: 130,
    rating: 4.9,
    flavor: "Oreo",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Premium",
    isAvailable: true,
    tagline: "Oreo lovers’ favorite.",
    image: "https://picsum.photos/seed/oreo/300/300"
  },
  {
    id: 17,
    name: "Rocky Road",
    price: 145,
    rating: 4.6,
    flavor: "Chocolate Nuts",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Premium",
    isAvailable: true,
    tagline: "Marshmallow and nut crunch.",
    image: "https://picsum.photos/seed/rockyroad/300/300"
  },
  {
    id: 18,
    name: "Watermelon Chill",
    price: 85,
    rating: 4.1,
    flavor: "Watermelon",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fruit",
    isAvailable: true,
    tagline: "Summer freshness scoop.",
    image: "https://picsum.photos/seed/watermelon/300/300"
  },
  {
    id: 19,
    name: "Bubblegum Fun",
    price: 90,
    rating: 4.0,
    flavor: "Bubblegum",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Kids",
    isAvailable: true,
    tagline: "Fun flavor for kids.",
    image: "https://picsum.photos/seed/bubblegum/300/300"
  },
  {
    id: 20,
    name: "Dark Chocolate",
    price: 135,
    rating: 4.8,
    flavor: "Dark Chocolate",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Premium",
    isAvailable: true,
    tagline: "Bold and intense cocoa.",
    image: "https://picsum.photos/seed/darkchoco/300/300"
  },
  {
    id: 21,
    name: "Honey Almond",
    price: 125,
    rating: 4.5,
    flavor: "Honey Almond",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Fusion",
    isAvailable: true,
    tagline: "Sweet honey with almond crunch.",
    image: "https://picsum.photos/seed/honeyalmond/300/300"
  },
  {
    id: 22,
    name: "Rainbow Scoop",
    price: 150,
    rating: 4.9,
    flavor: "Mixed",
    sizes: ["500ml", "1L"],
    discountPercent: 12,
     discountedPrice: 70,
    popularity: 95,
     discountPercent: 12,
    category: "Special",
    isAvailable: true,
    tagline: "All flavors in one scoop.",
    image: "https://picsum.photos/seed/rainbow/300/300"
  }
];

module.exports = iceCreams;
